# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TheLinuxWay
email: alocin05@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm not a teacher, nor an estimated veteran, I'm only a student and a
  linux lover. This page has the selfish purpose of impress and clarify
  concepts in my ming on my way through the linux world.
  With the only hope that some pious soul will criticize and will yell at me
  for all the bullshit I will write.
  I will try to make presentable all the personal handbooks written in years
  hoping that could be helpful for someone in the same way they're still helpful for me.
  Ah ok, and I will finally give a try to jekyll and markdown.
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  nicanz

# Build settings
markdown: kramdown
# theme: jekyll-theme-midnight
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
